### ISSUE TITLE
Exporter PR under Windows populates data directory field by default

### ISSUE THREAD

**Issue by GenevieveGorrell** [GateNLP/gateplugin-LearningFramework#69]
The data directory field is set to the GATE installation location by default instead of blank, as is usual.

**Comment by ianroberts** [comment]
The same happens on Mac, and this seems to be a deliberate choice in the code (ed539fe14ad7d4eff60be7eff2e35d396c49cbf3).

**Comment by johann-petrak** [comment]
For some reason I decided that the dataDirectory parameter for the Exporter PR is not required, as for the other PRs and made it get initialized with the current running directory of the Java process.
Cannot remember why I made it optional, probably to simplify using the PR from the command line without clumsily having to set the parameter.

The reason why it shows the GATE installation location is probably because some ways of starting GATE use that location as the current running directory. When using the command `gate.sh -tmp` it would be the current directory from where that command is run instead.

This should get changed to still be an optional parameter, but allow it to be left empty and use the current running directory internally if it is left blank.
